services:
  frontend_deploy:
    image: uni-datateam_frontend_deploy:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend_deploy
    restart: always

  backend_deploy:
    image: uni-datateam_backend_deploy:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge