
version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/sakai-vue
      dockerfile: ../Dockerfile.dev
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/springbootquickstart
      dockerfile: ../Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DATABASE_URL: jdbc:mysql://database:3306/yourdb
    networks:
      - app-network
networks:
  app-network:
    driver: bridge